# Generated by Django 6.0.5 on 2026-05-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_owners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owners',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
