# Generated by Django 6.0.5 on 2026-05-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_delete_owners_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
